In [1]:
import numpy as np

In [2]:
array1 = np.array([2,3,5,7,11,13,17,19, 23, 29, 31])

In [3]:
array1 > 4 #array1 리스트가 요소가 4보다 큰지 작은지 확인해서 True, False 반환

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [4]:
array1 % 2 == 0 # 짝수인 수는 True 홀수이면 False 반환

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [5]:
booleans = np.array([True, True, False, True, True, False, True, True, False, True])

In [6]:
np.where(booleans)  #True 인 값곳의 index만 출력

(array([0, 1, 3, 4, 6, 7, 9]),)

In [10]:
array1 > 4
np.where(array1 > 4) #->array 1에서 4보다 큰 값을 반환
#np.where(리스트명)를 통해 필요한 조건에 맞는 리스트 요소만 가지고 올 수 있음
filter = np.where(array1 > 4)
filter


(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)